### ISSUE TITLE
config_encoder_filters should be jtyr.config_encoder_filters in meta/main.yml

### ISSUE THREAD

**Issue by 030** [jtyr/ansible-qpid_cpp_server#3]
```
ERROR! the role 'config_encoder_filters' was not found in /ansible/roles:/tmp:/tmp:/ansible

The error appears to have been in '/tmp/ansible-qpid_cpp_server/meta/main.yml': line 16, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

dependencies:
  - config_encoder_filters
    ^ here

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by jtyr** [comment]
Please follow the instructions how to install the `config_encoder_filters` role:

https://github.com/jtyr/ansible-config_encoder_filters#installation

**Comment by 030** [comment]
I have updated the title

**Comment by 030** [comment]
```
- src: jtyr.config_encoder_filters
  version: v1.3
```

has been defined in the requirements file and it is deployed as jtyr.config_encoder_filters

**Comment by jtyr** [comment]
I'm sorry, but in my roles, I don't support role naming schema required by the Ansible Galaxy. The reason behind this is that where ever I worked, they never named their roles according to the Ansible Galaxy schema `<user>.<role>`. It was always either `<role>` or `ansible-<role>` because they never used multiple roles to manage the same thing thing (e.g. `john.nginx` and `doe.nginx`). Unfortunately the `requirements.yaml` file doesn't allow to specify the destination directory like this:

```
- src: https://github.com/jtyr/ansible-config_encoder_filters
  dest: config_encoder_filters
```

This is why I [recommend](http://www.slideshare.net/jtyr/automation-and-ansible#14) to use more advanced tool called [Android Repo Script](https://source.android.com/source/using-repo.html) instead.

**Comment by jtyr** [comment]
Actually, Ansible Galaxy supports renaming of the role:

```
$ cat ./requirements.yaml
---

- src: https://github.com/jtyr/ansible-config_encoder_filters.git
  name: config_encoder_filters
$ ansible-galaxy -r ./requirements.yaml
```

The problem with Ansible Galaxy is that it allows to download only roles but not other Git repositories (e.g. containing `group_vars`, `host_vars`, inventory, ...) unless they contain the meta file. This is where Android Repo Script is better.

I have updated the [installation instructions](https://github.com/jtyr/ansible-config_encoder_filters#installation) of the role with the above solution.
